name: build

on:
  workflow_call:

jobs:

  build:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/switstack/docker-alpine:latest

    steps:
  
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apk update
          apk add cpputest

      - name: Build
        run: make

      - name: Test
        run: make test
